pacman -S
    pipewire-jack \
    noto-fonts \
    noto-fonts-cjk \
    noto-fonts-emoji \
    ttf-font-awesome \
    fcitx5-mozc \
    fcitx5-configtool \
    gcc \
    python \
    rustup \
    firefox \
    foot \
    git \
    xorg-server-xwayland \
    qt5-wayland \
    sway \
    swaybg \
    polkit \
    waybar \
    wofi \
    man-db \
    vim \
    nano \
    zsh \
    grml-zsh-config \
    zsh-autosuggestions \
    zsh-completions \
    zsh-syntax-highlighting \
    networkmanager \
    wpa_supplicant \
    dialog \
    iw \
    dhcpcd \
    netctl \
    wayvnc \
    base-devel